// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_ADMIN       Role = 1
	Role_ROLE_MANAGER     Role = 2
	Role_ROLE_USER        Role = 3
)

var Role_name = map[int32]string{
	0: "ROLE_UNSPECIFIED",
	1: "ROLE_ADMIN",
	2: "ROLE_MANAGER",
	3: "ROLE_USER",
}

var Role_value = map[string]int32{
	"ROLE_UNSPECIFIED": 0,
	"ROLE_ADMIN":       1,
	"ROLE_MANAGER":     2,
	"ROLE_USER":        3,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type Scope int32

const (
	Scope_SCOPE_UNSPECIFIED Scope = 0
	Scope_SCOPE_USERS       Scope = 1
	Scope_SCOPE_TRACKINGS   Scope = 2
	Scope_SCOPE_PERMISSIONS Scope = 3
)

var Scope_name = map[int32]string{
	0: "SCOPE_UNSPECIFIED",
	1: "SCOPE_USERS",
	2: "SCOPE_TRACKINGS",
	3: "SCOPE_PERMISSIONS",
}

var Scope_value = map[string]int32{
	"SCOPE_UNSPECIFIED": 0,
	"SCOPE_USERS":       1,
	"SCOPE_TRACKINGS":   2,
	"SCOPE_PERMISSIONS": 3,
}

func (x Scope) String() string {
	return proto.EnumName(Scope_name, int32(x))
}

func (Scope) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_READ        Action = 1
	Action_ACTION_UPDATE      Action = 2
	Action_ACTION_DELETE      Action = 3
)

var Action_name = map[int32]string{
	0: "ACTION_UNSPECIFIED",
	1: "ACTION_READ",
	2: "ACTION_UPDATE",
	3: "ACTION_DELETE",
}

var Action_value = map[string]int32{
	"ACTION_UNSPECIFIED": 0,
	"ACTION_READ":        1,
	"ACTION_UPDATE":      2,
	"ACTION_DELETE":      3,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

type CreateAdminRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdminRequest) Reset()         { *m = CreateAdminRequest{} }
func (m *CreateAdminRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAdminRequest) ProtoMessage()    {}
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *CreateAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdminRequest.Unmarshal(m, b)
}
func (m *CreateAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdminRequest.Marshal(b, m, deterministic)
}
func (m *CreateAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdminRequest.Merge(m, src)
}
func (m *CreateAdminRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAdminRequest.Size(m)
}
func (m *CreateAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdminRequest proto.InternalMessageInfo

func (m *CreateAdminRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAdminRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateAdminResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdminResponse) Reset()         { *m = CreateAdminResponse{} }
func (m *CreateAdminResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAdminResponse) ProtoMessage()    {}
func (*CreateAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CreateAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdminResponse.Unmarshal(m, b)
}
func (m *CreateAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdminResponse.Marshal(b, m, deterministic)
}
func (m *CreateAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdminResponse.Merge(m, src)
}
func (m *CreateAdminResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAdminResponse.Size(m)
}
func (m *CreateAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdminResponse proto.InternalMessageInfo

func (m *CreateAdminResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddPermissionRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Scope                Scope    `protobuf:"varint,2,opt,name=scope,proto3,enum=api.Scope" json:"scope,omitempty"`
	Action               Action   `protobuf:"varint,3,opt,name=action,proto3,enum=api.Action" json:"action,omitempty"`
	Item                 string   `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPermissionRequest) Reset()         { *m = AddPermissionRequest{} }
func (m *AddPermissionRequest) String() string { return proto.CompactTextString(m) }
func (*AddPermissionRequest) ProtoMessage()    {}
func (*AddPermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *AddPermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPermissionRequest.Unmarshal(m, b)
}
func (m *AddPermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPermissionRequest.Marshal(b, m, deterministic)
}
func (m *AddPermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPermissionRequest.Merge(m, src)
}
func (m *AddPermissionRequest) XXX_Size() int {
	return xxx_messageInfo_AddPermissionRequest.Size(m)
}
func (m *AddPermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPermissionRequest proto.InternalMessageInfo

func (m *AddPermissionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddPermissionRequest) GetScope() Scope {
	if m != nil {
		return m.Scope
	}
	return Scope_SCOPE_UNSPECIFIED
}

func (m *AddPermissionRequest) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (m *AddPermissionRequest) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

type AddRoleRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Role                 Role     `protobuf:"varint,2,opt,name=role,proto3,enum=api.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRoleRequest) Reset()         { *m = AddRoleRequest{} }
func (m *AddRoleRequest) String() string { return proto.CompactTextString(m) }
func (*AddRoleRequest) ProtoMessage()    {}
func (*AddRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *AddRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRoleRequest.Unmarshal(m, b)
}
func (m *AddRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRoleRequest.Marshal(b, m, deterministic)
}
func (m *AddRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRoleRequest.Merge(m, src)
}
func (m *AddRoleRequest) XXX_Size() int {
	return xxx_messageInfo_AddRoleRequest.Size(m)
}
func (m *AddRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRoleRequest proto.InternalMessageInfo

func (m *AddRoleRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddRoleRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_ROLE_UNSPECIFIED
}

type RemoveRoleRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Role                 Role     `protobuf:"varint,2,opt,name=role,proto3,enum=api.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRoleRequest) Reset()         { *m = RemoveRoleRequest{} }
func (m *RemoveRoleRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRoleRequest) ProtoMessage()    {}
func (*RemoveRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *RemoveRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRoleRequest.Unmarshal(m, b)
}
func (m *RemoveRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRoleRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRoleRequest.Merge(m, src)
}
func (m *RemoveRoleRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRoleRequest.Size(m)
}
func (m *RemoveRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRoleRequest proto.InternalMessageInfo

func (m *RemoveRoleRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RemoveRoleRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_ROLE_UNSPECIFIED
}

type SignUpRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignUpResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SignInRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	RefreshToken         string               `protobuf:"bytes,1,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	AccessToken          string               `protobuf:"bytes,2,opt,name=access_token,proto3" json:"access_token,omitempty"`
	ExpireAt             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expire_at,proto3" json:"expire_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *SignInResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *SignInResponse) GetExpireAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpireAt
	}
	return nil
}

type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ListUsersRequest struct {
	PerReq               int64    `protobuf:"varint,1,opt,name=per_req,proto3" json:"per_req,omitempty"`
	Cursor               string   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetPerReq() int64 {
	if m != nil {
		return m.PerReq
	}
	return 0
}

func (m *ListUsersRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *ListUsersRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ListUsersResponse struct {
	Cursor               string   `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Users                []*User  `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *ListUsersResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type ListUsersDetailedResponse struct {
	Cursor               string          `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Total                int64           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Users                []*DetailedUser `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListUsersDetailedResponse) Reset()         { *m = ListUsersDetailedResponse{} }
func (m *ListUsersDetailedResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersDetailedResponse) ProtoMessage()    {}
func (*ListUsersDetailedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *ListUsersDetailedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersDetailedResponse.Unmarshal(m, b)
}
func (m *ListUsersDetailedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersDetailedResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersDetailedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersDetailedResponse.Merge(m, src)
}
func (m *ListUsersDetailedResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersDetailedResponse.Size(m)
}
func (m *ListUsersDetailedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersDetailedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersDetailedResponse proto.InternalMessageInfo

func (m *ListUsersDetailedResponse) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *ListUsersDetailedResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListUsersDetailedResponse) GetUsers() []*DetailedUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type DeleteUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RefreshTokenRequest struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRequest) Reset()         { *m = RefreshTokenRequest{} }
func (m *RefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRequest) ProtoMessage()    {}
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *RefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRequest.Unmarshal(m, b)
}
func (m *RefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRequest.Merge(m, src)
}
func (m *RefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRequest.Size(m)
}
func (m *RefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRequest proto.InternalMessageInfo

func (m *RefreshTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	RefreshToken         string               `protobuf:"bytes,1,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	AccessToken          string               `protobuf:"bytes,2,opt,name=access_token,proto3" json:"access_token,omitempty"`
	ExpireAt             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expire_at,proto3" json:"expire_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RefreshTokenResponse) Reset()         { *m = RefreshTokenResponse{} }
func (m *RefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenResponse) ProtoMessage()    {}
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *RefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenResponse.Unmarshal(m, b)
}
func (m *RefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenResponse.Merge(m, src)
}
func (m *RefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenResponse.Size(m)
}
func (m *RefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenResponse proto.InternalMessageInfo

func (m *RefreshTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *RefreshTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RefreshTokenResponse) GetExpireAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpireAt
	}
	return nil
}

type CreateTrackingRequest struct {
	Date                 string             `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Time                 *duration.Duration `protobuf:"bytes,2,opt,name=time,json=duration,proto3" json:"time,omitempty"`
	Distance             float32            `protobuf:"fixed32,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Location             *Location          `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateTrackingRequest) Reset()         { *m = CreateTrackingRequest{} }
func (m *CreateTrackingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTrackingRequest) ProtoMessage()    {}
func (*CreateTrackingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *CreateTrackingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTrackingRequest.Unmarshal(m, b)
}
func (m *CreateTrackingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTrackingRequest.Marshal(b, m, deterministic)
}
func (m *CreateTrackingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTrackingRequest.Merge(m, src)
}
func (m *CreateTrackingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTrackingRequest.Size(m)
}
func (m *CreateTrackingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTrackingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTrackingRequest proto.InternalMessageInfo

func (m *CreateTrackingRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *CreateTrackingRequest) GetTime() *duration.Duration {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *CreateTrackingRequest) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *CreateTrackingRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type CreateTrackingResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTrackingResponse) Reset()         { *m = CreateTrackingResponse{} }
func (m *CreateTrackingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTrackingResponse) ProtoMessage()    {}
func (*CreateTrackingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *CreateTrackingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTrackingResponse.Unmarshal(m, b)
}
func (m *CreateTrackingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTrackingResponse.Marshal(b, m, deterministic)
}
func (m *CreateTrackingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTrackingResponse.Merge(m, src)
}
func (m *CreateTrackingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTrackingResponse.Size(m)
}
func (m *CreateTrackingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTrackingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTrackingResponse proto.InternalMessageInfo

func (m *CreateTrackingResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteTrackingRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTrackingRequest) Reset()         { *m = DeleteTrackingRequest{} }
func (m *DeleteTrackingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTrackingRequest) ProtoMessage()    {}
func (*DeleteTrackingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *DeleteTrackingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTrackingRequest.Unmarshal(m, b)
}
func (m *DeleteTrackingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTrackingRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTrackingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTrackingRequest.Merge(m, src)
}
func (m *DeleteTrackingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTrackingRequest.Size(m)
}
func (m *DeleteTrackingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTrackingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTrackingRequest proto.InternalMessageInfo

func (m *DeleteTrackingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTrackingRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTrackingRequest) Reset()         { *m = GetTrackingRequest{} }
func (m *GetTrackingRequest) String() string { return proto.CompactTextString(m) }
func (*GetTrackingRequest) ProtoMessage()    {}
func (*GetTrackingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *GetTrackingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTrackingRequest.Unmarshal(m, b)
}
func (m *GetTrackingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTrackingRequest.Marshal(b, m, deterministic)
}
func (m *GetTrackingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTrackingRequest.Merge(m, src)
}
func (m *GetTrackingRequest) XXX_Size() int {
	return xxx_messageInfo_GetTrackingRequest.Size(m)
}
func (m *GetTrackingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTrackingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTrackingRequest proto.InternalMessageInfo

func (m *GetTrackingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTrackingResponse struct {
	Tracking             *Tracking `protobuf:"bytes,1,opt,name=tracking,proto3" json:"tracking,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTrackingResponse) Reset()         { *m = GetTrackingResponse{} }
func (m *GetTrackingResponse) String() string { return proto.CompactTextString(m) }
func (*GetTrackingResponse) ProtoMessage()    {}
func (*GetTrackingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *GetTrackingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTrackingResponse.Unmarshal(m, b)
}
func (m *GetTrackingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTrackingResponse.Marshal(b, m, deterministic)
}
func (m *GetTrackingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTrackingResponse.Merge(m, src)
}
func (m *GetTrackingResponse) XXX_Size() int {
	return xxx_messageInfo_GetTrackingResponse.Size(m)
}
func (m *GetTrackingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTrackingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTrackingResponse proto.InternalMessageInfo

func (m *GetTrackingResponse) GetTracking() *Tracking {
	if m != nil {
		return m.Tracking
	}
	return nil
}

type ListTrackingsRequest struct {
	PerReq               int64    `protobuf:"varint,1,opt,name=per_req,proto3" json:"per_req,omitempty"`
	Cursor               string   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTrackingsRequest) Reset()         { *m = ListTrackingsRequest{} }
func (m *ListTrackingsRequest) String() string { return proto.CompactTextString(m) }
func (*ListTrackingsRequest) ProtoMessage()    {}
func (*ListTrackingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *ListTrackingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTrackingsRequest.Unmarshal(m, b)
}
func (m *ListTrackingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTrackingsRequest.Marshal(b, m, deterministic)
}
func (m *ListTrackingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTrackingsRequest.Merge(m, src)
}
func (m *ListTrackingsRequest) XXX_Size() int {
	return xxx_messageInfo_ListTrackingsRequest.Size(m)
}
func (m *ListTrackingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTrackingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTrackingsRequest proto.InternalMessageInfo

func (m *ListTrackingsRequest) GetPerReq() int64 {
	if m != nil {
		return m.PerReq
	}
	return 0
}

func (m *ListTrackingsRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *ListTrackingsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ListTrackingsResponse struct {
	Cursor               string      `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Total                int64       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Trackings            []*Tracking `protobuf:"bytes,3,rep,name=trackings,json=tracking,proto3" json:"trackings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListTrackingsResponse) Reset()         { *m = ListTrackingsResponse{} }
func (m *ListTrackingsResponse) String() string { return proto.CompactTextString(m) }
func (*ListTrackingsResponse) ProtoMessage()    {}
func (*ListTrackingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{23}
}

func (m *ListTrackingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTrackingsResponse.Unmarshal(m, b)
}
func (m *ListTrackingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTrackingsResponse.Marshal(b, m, deterministic)
}
func (m *ListTrackingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTrackingsResponse.Merge(m, src)
}
func (m *ListTrackingsResponse) XXX_Size() int {
	return xxx_messageInfo_ListTrackingsResponse.Size(m)
}
func (m *ListTrackingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTrackingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTrackingsResponse proto.InternalMessageInfo

func (m *ListTrackingsResponse) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *ListTrackingsResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListTrackingsResponse) GetTrackings() []*Tracking {
	if m != nil {
		return m.Trackings
	}
	return nil
}

type ReportRequest struct {
	FromDate             string             `protobuf:"bytes,1,opt,name=from_date,proto3" json:"from_date,omitempty"`
	Duration             *duration.Duration `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{24}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetFromDate() string {
	if m != nil {
		return m.FromDate
	}
	return ""
}

func (m *ReportRequest) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type ReportResponse struct {
	AverageSpeed         float32  `protobuf:"fixed32,1,opt,name=average_speed,proto3" json:"average_speed,omitempty"`
	Distance             float32  `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportResponse) Reset()         { *m = ReportResponse{} }
func (m *ReportResponse) String() string { return proto.CompactTextString(m) }
func (*ReportResponse) ProtoMessage()    {}
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{25}
}

func (m *ReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportResponse.Unmarshal(m, b)
}
func (m *ReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportResponse.Marshal(b, m, deterministic)
}
func (m *ReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportResponse.Merge(m, src)
}
func (m *ReportResponse) XXX_Size() int {
	return xxx_messageInfo_ReportResponse.Size(m)
}
func (m *ReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportResponse proto.InternalMessageInfo

func (m *ReportResponse) GetAverageSpeed() float32 {
	if m != nil {
		return m.AverageSpeed
	}
	return 0
}

func (m *ReportResponse) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{26}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type DetailedUser struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Roles                []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions          []string `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailedUser) Reset()         { *m = DetailedUser{} }
func (m *DetailedUser) String() string { return proto.CompactTextString(m) }
func (*DetailedUser) ProtoMessage()    {}
func (*DetailedUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{27}
}

func (m *DetailedUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailedUser.Unmarshal(m, b)
}
func (m *DetailedUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailedUser.Marshal(b, m, deterministic)
}
func (m *DetailedUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailedUser.Merge(m, src)
}
func (m *DetailedUser) XXX_Size() int {
	return xxx_messageInfo_DetailedUser.Size(m)
}
func (m *DetailedUser) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailedUser.DiscardUnknown(m)
}

var xxx_messageInfo_DetailedUser proto.InternalMessageInfo

func (m *DetailedUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DetailedUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DetailedUser) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *DetailedUser) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type Tracking struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string             `protobuf:"bytes,2,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Date                 string             `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Time                 *duration.Duration `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Distance             float32            `protobuf:"fixed32,5,opt,name=distance,proto3" json:"distance,omitempty"`
	Location             *Location          `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Weather              *Weather           `protobuf:"bytes,7,opt,name=weather,proto3" json:"weather,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Tracking) Reset()         { *m = Tracking{} }
func (m *Tracking) String() string { return proto.CompactTextString(m) }
func (*Tracking) ProtoMessage()    {}
func (*Tracking) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{28}
}

func (m *Tracking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracking.Unmarshal(m, b)
}
func (m *Tracking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracking.Marshal(b, m, deterministic)
}
func (m *Tracking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracking.Merge(m, src)
}
func (m *Tracking) XXX_Size() int {
	return xxx_messageInfo_Tracking.Size(m)
}
func (m *Tracking) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracking.DiscardUnknown(m)
}

var xxx_messageInfo_Tracking proto.InternalMessageInfo

func (m *Tracking) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tracking) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Tracking) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Tracking) GetTime() *duration.Duration {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Tracking) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *Tracking) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Tracking) GetWeather() *Weather {
	if m != nil {
		return m.Weather
	}
	return nil
}

type Location struct {
	Longitude            float64  `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{29}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type Weather struct {
	Temperature          float32  `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TemperatureMin       float32  `protobuf:"fixed32,2,opt,name=temperature_min,proto3" json:"temperature_min,omitempty"`
	TemperatureMax       float32  `protobuf:"fixed32,3,opt,name=temperature_max,proto3" json:"temperature_max,omitempty"`
	Snowdepth            float32  `protobuf:"fixed32,4,opt,name=snowdepth,proto3" json:"snowdepth,omitempty"`
	Winddirection        float32  `protobuf:"fixed32,5,opt,name=winddirection,proto3" json:"winddirection,omitempty"`
	Windspeed            float32  `protobuf:"fixed32,6,opt,name=windspeed,proto3" json:"windspeed,omitempty"`
	Pressure             float32  `protobuf:"fixed32,7,opt,name=pressure,proto3" json:"pressure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weather) Reset()         { *m = Weather{} }
func (m *Weather) String() string { return proto.CompactTextString(m) }
func (*Weather) ProtoMessage()    {}
func (*Weather) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{30}
}

func (m *Weather) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weather.Unmarshal(m, b)
}
func (m *Weather) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weather.Marshal(b, m, deterministic)
}
func (m *Weather) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weather.Merge(m, src)
}
func (m *Weather) XXX_Size() int {
	return xxx_messageInfo_Weather.Size(m)
}
func (m *Weather) XXX_DiscardUnknown() {
	xxx_messageInfo_Weather.DiscardUnknown(m)
}

var xxx_messageInfo_Weather proto.InternalMessageInfo

func (m *Weather) GetTemperature() float32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *Weather) GetTemperatureMin() float32 {
	if m != nil {
		return m.TemperatureMin
	}
	return 0
}

func (m *Weather) GetTemperatureMax() float32 {
	if m != nil {
		return m.TemperatureMax
	}
	return 0
}

func (m *Weather) GetSnowdepth() float32 {
	if m != nil {
		return m.Snowdepth
	}
	return 0
}

func (m *Weather) GetWinddirection() float32 {
	if m != nil {
		return m.Winddirection
	}
	return 0
}

func (m *Weather) GetWindspeed() float32 {
	if m != nil {
		return m.Windspeed
	}
	return 0
}

func (m *Weather) GetPressure() float32 {
	if m != nil {
		return m.Pressure
	}
	return 0
}

func init() {
	proto.RegisterEnum("api.Role", Role_name, Role_value)
	proto.RegisterEnum("api.Scope", Scope_name, Scope_value)
	proto.RegisterEnum("api.Action", Action_name, Action_value)
	proto.RegisterType((*CreateAdminRequest)(nil), "api.CreateAdminRequest")
	proto.RegisterType((*CreateAdminResponse)(nil), "api.CreateAdminResponse")
	proto.RegisterType((*AddPermissionRequest)(nil), "api.AddPermissionRequest")
	proto.RegisterType((*AddRoleRequest)(nil), "api.AddRoleRequest")
	proto.RegisterType((*RemoveRoleRequest)(nil), "api.RemoveRoleRequest")
	proto.RegisterType((*SignUpRequest)(nil), "api.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "api.SignUpResponse")
	proto.RegisterType((*SignInRequest)(nil), "api.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "api.SignInResponse")
	proto.RegisterType((*GetUserRequest)(nil), "api.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "api.GetUserResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "api.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "api.ListUsersResponse")
	proto.RegisterType((*ListUsersDetailedResponse)(nil), "api.ListUsersDetailedResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "api.DeleteUserRequest")
	proto.RegisterType((*RefreshTokenRequest)(nil), "api.RefreshTokenRequest")
	proto.RegisterType((*RefreshTokenResponse)(nil), "api.RefreshTokenResponse")
	proto.RegisterType((*CreateTrackingRequest)(nil), "api.CreateTrackingRequest")
	proto.RegisterType((*CreateTrackingResponse)(nil), "api.CreateTrackingResponse")
	proto.RegisterType((*DeleteTrackingRequest)(nil), "api.DeleteTrackingRequest")
	proto.RegisterType((*GetTrackingRequest)(nil), "api.GetTrackingRequest")
	proto.RegisterType((*GetTrackingResponse)(nil), "api.GetTrackingResponse")
	proto.RegisterType((*ListTrackingsRequest)(nil), "api.ListTrackingsRequest")
	proto.RegisterType((*ListTrackingsResponse)(nil), "api.ListTrackingsResponse")
	proto.RegisterType((*ReportRequest)(nil), "api.ReportRequest")
	proto.RegisterType((*ReportResponse)(nil), "api.ReportResponse")
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*DetailedUser)(nil), "api.DetailedUser")
	proto.RegisterType((*Tracking)(nil), "api.Tracking")
	proto.RegisterType((*Location)(nil), "api.Location")
	proto.RegisterType((*Weather)(nil), "api.Weather")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1872 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xeb, 0x6e, 0xdb, 0xc8,
	0x15, 0x36, 0x25, 0x59, 0x97, 0x23, 0x4b, 0x96, 0xc7, 0x97, 0xc8, 0x4c, 0xb2, 0x16, 0x98, 0x4d,
	0x37, 0xab, 0x5d, 0x4b, 0x89, 0x7b, 0x41, 0xb1, 0xfd, 0x13, 0xd9, 0xd2, 0x06, 0xda, 0xda, 0x8e,
	0x43, 0x39, 0x49, 0x9b, 0x2d, 0x2a, 0xd0, 0xe2, 0x98, 0x66, 0x23, 0x71, 0x18, 0x92, 0xb2, 0x37,
	0xbb, 0x08, 0x50, 0x14, 0xe8, 0x0b, 0xb4, 0xfd, 0xd5, 0x57, 0xe8, 0x2b, 0xf4, 0x47, 0xdf, 0xa1,
	0xe8, 0xef, 0x00, 0x41, 0xd1, 0xb7, 0x28, 0x50, 0xcc, 0x8d, 0x37, 0x49, 0x4d, 0x1a, 0xa4, 0xc0,
	0xfa, 0x8f, 0xc5, 0x33, 0xdf, 0x7c, 0xe7, 0xcc, 0xb9, 0xcc, 0x9c, 0x03, 0x25, 0xc3, 0xb5, 0x5b,
	0xae, 0x47, 0x02, 0x82, 0xb2, 0x86, 0x6b, 0xab, 0xd7, 0x2d, 0x42, 0xac, 0x31, 0x6e, 0x33, 0xd1,
	0xd9, 0xf4, 0xbc, 0x8d, 0x27, 0x6e, 0xf0, 0x92, 0x23, 0xd4, 0x9d, 0xf4, 0x62, 0x60, 0x4f, 0xb0,
	0x1f, 0x18, 0x13, 0x57, 0x00, 0x3e, 0x4a, 0x03, 0xcc, 0xa9, 0x67, 0x04, 0x36, 0x71, 0xc4, 0xfa,
	0x0d, 0xb1, 0x6e, 0xb8, 0x76, 0xdb, 0x70, 0x1c, 0x12, 0xb0, 0x45, 0x5f, 0xac, 0x7e, 0xce, 0xfe,
	0x8d, 0x76, 0x2d, 0xec, 0xec, 0xfa, 0x57, 0x86, 0x65, 0x61, 0xaf, 0x4d, 0x5c, 0x86, 0x98, 0x83,
	0xfe, 0x89, 0x65, 0x07, 0x17, 0xd3, 0xb3, 0xd6, 0x88, 0x4c, 0xda, 0x93, 0x2b, 0x3b, 0x78, 0x4e,
	0xae, 0xda, 0x16, 0xd9, 0x65, 0x8b, 0xbb, 0x97, 0xc6, 0xd8, 0x36, 0x8d, 0x80, 0x78, 0x7e, 0x3b,
	0xfc, 0xc9, 0xf7, 0x69, 0x4f, 0x00, 0x1d, 0x78, 0xd8, 0x08, 0x70, 0xc7, 0x9c, 0xd8, 0x8e, 0x8e,
	0x5f, 0x4c, 0xb1, 0x1f, 0xa0, 0x1b, 0xb0, 0x8c, 0x27, 0x86, 0x3d, 0xae, 0x2b, 0x0d, 0xe5, 0x4e,
	0x69, 0x3f, 0xff, 0xe6, 0xf5, 0x4e, 0xe6, 0x17, 0x8a, 0xce, 0x85, 0x48, 0x83, 0xa2, 0x6b, 0xf8,
	0xfe, 0x15, 0xf1, 0xcc, 0x7a, 0x26, 0x01, 0x08, 0xe5, 0xda, 0x6d, 0x58, 0x4f, 0xf0, 0xfa, 0x2e,
	0x71, 0x7c, 0x8c, 0xaa, 0x90, 0xb1, 0x4d, 0xce, 0xaa, 0x67, 0x6c, 0x53, 0xfb, 0x8b, 0x02, 0x1b,
	0x1d, 0xd3, 0x3c, 0xc1, 0xde, 0xc4, 0xf6, 0x7d, 0x9b, 0x84, 0x16, 0x34, 0xa0, 0x30, 0xf5, 0xb1,
	0x37, 0x94, 0xe8, 0x50, 0x85, 0x14, 0xa3, 0x3b, 0xb0, 0xec, 0x8f, 0x88, 0x8b, 0x99, 0x09, 0xd5,
	0x3d, 0x68, 0xd1, 0xd8, 0x0d, 0xa8, 0x24, 0xb2, 0x97, 0x01, 0xd0, 0x67, 0x90, 0x37, 0x46, 0xd4,
	0x59, 0xf5, 0x2c, 0x83, 0x96, 0x19, 0xb4, 0xc3, 0x44, 0x21, 0x56, 0x40, 0x90, 0x0a, 0x39, 0x3b,
	0xc0, 0x93, 0x7a, 0x2e, 0xa1, 0x95, 0xc9, 0xb4, 0x5f, 0x42, 0xb5, 0x63, 0x9a, 0x3a, 0x19, 0xe3,
	0x77, 0x37, 0xf3, 0x36, 0xe4, 0x3c, 0x32, 0x96, 0x56, 0x96, 0x98, 0x6a, 0xca, 0x10, 0x51, 0xd3,
	0x65, 0xed, 0x57, 0xb0, 0xa6, 0xe3, 0x09, 0xb9, 0xc4, 0xff, 0x17, 0xf6, 0x47, 0x50, 0x19, 0xd8,
	0x96, 0xf3, 0xd8, 0xfd, 0x70, 0x01, 0x6e, 0x40, 0x55, 0x52, 0x2e, 0x88, 0x6d, 0x87, 0x2b, 0xed,
	0x87, 0x31, 0xdd, 0x48, 0x28, 0x95, 0xca, 0xd4, 0xb4, 0xb2, 0x98, 0x92, 0x3f, 0x29, 0x5c, 0x4b,
	0x3f, 0xca, 0xa0, 0x8f, 0xa1, 0xe2, 0xe1, 0x73, 0x0f, 0xfb, 0x17, 0xc3, 0x80, 0x3c, 0xc7, 0x8e,
	0x20, 0x4b, 0x0a, 0x91, 0x06, 0x2b, 0xc6, 0x68, 0x84, 0x7d, 0x5f, 0x80, 0x38, 0x71, 0x42, 0x86,
	0x7e, 0x0a, 0x25, 0xfc, 0x8d, 0x6b, 0x7b, 0x78, 0x68, 0x04, 0x2c, 0x33, 0xca, 0x7b, 0x6a, 0x8b,
	0x97, 0x64, 0x4b, 0x96, 0x6c, 0xeb, 0x54, 0xd6, 0xb4, 0x1e, 0x81, 0xe9, 0xd9, 0x1f, 0xe0, 0xe0,
	0xb1, 0x8f, 0x3d, 0x79, 0xb4, 0xf4, 0xd9, 0xef, 0xc2, 0x6a, 0x88, 0x10, 0x86, 0xdf, 0x84, 0x1c,
	0x8d, 0x1a, 0x03, 0x95, 0x45, 0xa8, 0x18, 0x80, 0x89, 0xb5, 0x67, 0x50, 0x3b, 0xb4, 0x7d, 0xb6,
	0xc5, 0x97, 0xac, 0x75, 0x28, 0xb8, 0xd8, 0x1b, 0x7a, 0xf8, 0x05, 0xdb, 0x95, 0xd5, 0xe5, 0x27,
	0xda, 0x82, 0xfc, 0x68, 0xea, 0xf9, 0xc4, 0x13, 0x27, 0x13, 0x5f, 0xd4, 0xc5, 0x2f, 0xa6, 0xd8,
	0x7b, 0xc9, 0xce, 0x53, 0xd2, 0xf9, 0x87, 0x76, 0x06, 0x6b, 0x31, 0x6e, 0x61, 0x4f, 0x44, 0xa1,
	0xa4, 0x29, 0x02, 0x12, 0x18, 0x63, 0xc6, 0x9c, 0xd5, 0xf9, 0x07, 0xda, 0x81, 0x65, 0x6a, 0xa6,
	0x5f, 0xcf, 0x36, 0xb2, 0x49, 0xf3, 0xb9, 0x5c, 0xf3, 0x60, 0x3b, 0xd4, 0xd1, 0xc5, 0x81, 0x61,
	0x8f, 0xb1, 0xf9, 0x9e, 0xba, 0x3e, 0x49, 0xea, 0x5a, 0x63, 0xba, 0x24, 0x67, 0x5c, 0xe7, 0x2d,
	0x58, 0xeb, 0xe2, 0x31, 0x0e, 0xf0, 0x7f, 0x0b, 0xc5, 0xcf, 0x60, 0x5d, 0xe7, 0xb9, 0x71, 0x4a,
	0xc3, 0x2e, 0x61, 0xef, 0x94, 0x47, 0xda, 0x9f, 0x15, 0xd8, 0x48, 0xee, 0xfe, 0x1e, 0xa5, 0xe1,
	0x5f, 0x15, 0xd8, 0xe4, 0x97, 0xec, 0xa9, 0x67, 0x8c, 0x9e, 0xdb, 0x8e, 0x25, 0x0f, 0x87, 0x20,
	0x67, 0x1a, 0x01, 0x16, 0x46, 0xb1, 0xdf, 0xe8, 0x1e, 0xe4, 0xe8, 0x03, 0xc5, 0x6c, 0x28, 0xef,
	0x6d, 0xcf, 0xa8, 0xe8, 0x8a, 0xc7, 0x49, 0x2f, 0xca, 0x67, 0x0a, 0x7d, 0x0a, 0x45, 0xd3, 0xf6,
	0x03, 0xc3, 0x19, 0x61, 0x66, 0x59, 0x66, 0xbf, 0xf2, 0xe6, 0xf5, 0x4e, 0xa9, 0xbf, 0x24, 0xfe,
	0xf4, 0x70, 0x19, 0xdd, 0x83, 0xe2, 0x98, 0x8c, 0xd8, 0x36, 0x76, 0x75, 0x96, 0xf7, 0x2a, 0x2c,
	0x6c, 0x87, 0x42, 0xc8, 0x6f, 0x90, 0x86, 0xa2, 0x87, 0x30, 0xed, 0x0e, 0x6c, 0xa5, 0xad, 0x5f,
	0x70, 0x93, 0x7c, 0x02, 0x9b, 0x3c, 0xce, 0xe9, 0x73, 0xa6, 0x81, 0x1f, 0x03, 0x7a, 0x80, 0x83,
	0xb7, 0xa1, 0xee, 0xc3, 0x7a, 0x02, 0x25, 0xb4, 0x7e, 0x0a, 0xc5, 0x40, 0xc8, 0x44, 0x91, 0xf2,
	0x23, 0x84, 0xc0, 0x70, 0x59, 0xfb, 0x35, 0x6c, 0xd0, 0x64, 0x97, 0x2b, 0x1f, 0xbc, 0x60, 0x5f,
	0xc0, 0x66, 0x8a, 0xff, 0xbd, 0x0a, 0xa9, 0x09, 0x25, 0x69, 0xb2, 0x2c, 0xa6, 0x85, 0x47, 0x32,
	0xa1, 0xa2, 0x63, 0x97, 0x78, 0x41, 0xf4, 0x44, 0x94, 0xce, 0x3d, 0x32, 0x19, 0xc6, 0x12, 0x29,
	0x12, 0xa0, 0x1f, 0x43, 0x98, 0x26, 0xff, 0x43, 0x46, 0x69, 0x3a, 0x54, 0xa5, 0x96, 0xa8, 0x90,
	0x8c, 0x4b, 0xec, 0x19, 0x16, 0x1e, 0xfa, 0x2e, 0xc6, 0x3c, 0x4e, 0x19, 0x3d, 0x29, 0xa4, 0x8f,
	0x44, 0x98, 0x89, 0x19, 0x06, 0x08, 0xbf, 0xb5, 0xcf, 0x21, 0x47, 0xeb, 0x3f, 0x1d, 0xe6, 0xe8,
	0xb9, 0xc9, 0xc4, 0x9e, 0x1b, 0x6d, 0x0c, 0x2b, 0xf1, 0xab, 0xe4, 0xdd, 0x76, 0x51, 0x29, 0x7d,
	0x48, 0xb9, 0x17, 0x4b, 0x3a, 0xff, 0x40, 0x0d, 0x28, 0xbb, 0x61, 0xe7, 0xe2, 0xd7, 0x73, 0x6c,
	0x2d, 0x2e, 0xd2, 0xfe, 0xa5, 0x40, 0x51, 0x3a, 0x7b, 0x46, 0x55, 0x3d, 0x7a, 0xde, 0xb9, 0xb2,
	0xf0, 0x59, 0x97, 0xf5, 0x9b, 0x8d, 0xd5, 0xef, 0xae, 0xa8, 0xdf, 0xdc, 0xdb, 0xbc, 0xcd, 0x60,
	0x09, 0x8f, 0x2d, 0x27, 0x3d, 0x46, 0x33, 0x3d, 0x2c, 0xd6, 0xfc, 0x9c, 0x62, 0x8d, 0x8a, 0x14,
	0xfd, 0x00, 0x0a, 0x57, 0xd8, 0x08, 0x2e, 0xb0, 0x57, 0x2f, 0x30, 0xe4, 0x0a, 0x43, 0x3e, 0xe5,
	0x32, 0x5d, 0x2e, 0x6a, 0x01, 0x14, 0xe5, 0x6e, 0xf4, 0x23, 0x28, 0x8d, 0x89, 0x63, 0xd9, 0xc1,
	0xd4, 0xe4, 0x99, 0xa3, 0xec, 0x6f, 0xbd, 0x79, 0xbd, 0x83, 0xf8, 0xbd, 0xf1, 0xdb, 0xf3, 0xbf,
	0x3d, 0x12, 0x3f, 0xee, 0xeb, 0x11, 0x10, 0xed, 0x41, 0x71, 0x6c, 0x04, 0x7c, 0x53, 0x66, 0x66,
	0xd3, 0x13, 0xb9, 0xe9, 0xc9, 0x7d, 0x3d, 0xc4, 0x69, 0xff, 0x56, 0xa0, 0x20, 0x4c, 0xa1, 0xc1,
	0x08, 0xf0, 0xc4, 0xc5, 0x9e, 0x11, 0x4c, 0x3d, 0x2c, 0xd2, 0x28, 0x2e, 0x42, 0x77, 0x60, 0x35,
	0xf6, 0x39, 0x9c, 0xd8, 0x8e, 0xc8, 0xa5, 0xb4, 0x78, 0x06, 0x69, 0x7c, 0xc3, 0xef, 0x3f, 0x3d,
	0x2d, 0xa6, 0x55, 0xe2, 0x3b, 0xe4, 0xca, 0xc4, 0x6e, 0x70, 0xc1, 0x42, 0x93, 0xd1, 0x23, 0x01,
	0x4d, 0xee, 0x2b, 0xdb, 0x31, 0x4d, 0xdb, 0xc3, 0xbc, 0x01, 0xe5, 0x91, 0x48, 0x0a, 0x29, 0x07,
	0x15, 0xf0, 0xf4, 0xcf, 0x73, 0x8e, 0x50, 0xc0, 0xfa, 0x23, 0x0f, 0xfb, 0x3e, 0x3d, 0x54, 0x81,
	0x07, 0x52, 0x7e, 0x37, 0x8f, 0x20, 0x47, 0xbb, 0x3d, 0xb4, 0x01, 0x35, 0xfd, 0xe1, 0x61, 0x6f,
	0xf8, 0xf8, 0x78, 0x70, 0xd2, 0x3b, 0xe8, 0x7f, 0xd9, 0xef, 0x75, 0x6b, 0x4b, 0xa8, 0x0a, 0xc0,
	0xa4, 0x9d, 0xee, 0x51, 0xff, 0xb8, 0xa6, 0xa0, 0x1a, 0xac, 0xb0, 0xef, 0xa3, 0xce, 0x71, 0xe7,
	0x41, 0x4f, 0xaf, 0x65, 0x50, 0x05, 0x4a, 0x7c, 0xdf, 0xa0, 0xa7, 0xd7, 0xb2, 0xcd, 0xaf, 0x61,
	0x99, 0x35, 0xd0, 0x68, 0x13, 0xd6, 0x06, 0x07, 0x0f, 0x4f, 0xd2, 0x84, 0xab, 0x50, 0x16, 0xe2,
	0x41, 0x4f, 0x1f, 0xd4, 0x14, 0xb4, 0x0e, 0xab, 0x5c, 0x70, 0xaa, 0x77, 0x0e, 0x7e, 0xde, 0x3f,
	0x7e, 0x30, 0xa8, 0x65, 0xa2, 0xcd, 0x27, 0x3d, 0xfd, 0xa8, 0x3f, 0x18, 0xf4, 0x1f, 0x1e, 0x0f,
	0x6a, 0xd9, 0xe6, 0x53, 0xc8, 0xf3, 0x96, 0x1b, 0x6d, 0x01, 0xea, 0x1c, 0x9c, 0xf6, 0x1f, 0x1e,
	0xcf, 0xd2, 0x0b, 0xb9, 0xde, 0xeb, 0x74, 0x6b, 0x0a, 0x5a, 0x83, 0x8a, 0x04, 0x9e, 0x74, 0x3b,
	0xa7, 0xbd, 0x5a, 0x26, 0x26, 0xea, 0xf6, 0x0e, 0x7b, 0xa7, 0xbd, 0x5a, 0x76, 0xef, 0x1f, 0x15,
	0x80, 0xce, 0x49, 0x7f, 0x80, 0xbd, 0x4b, 0x7b, 0x84, 0xd1, 0x3e, 0x94, 0x63, 0x93, 0x07, 0xba,
	0xc6, 0xf2, 0x75, 0x76, 0xc6, 0x51, 0xeb, 0xb3, 0x0b, 0xfc, 0x4a, 0xd2, 0x96, 0x90, 0x05, 0x95,
	0xc4, 0x54, 0x82, 0xb6, 0xf9, 0xc8, 0x30, 0x67, 0x52, 0x51, 0xb7, 0x66, 0x2a, 0xb1, 0x47, 0x87,
	0x44, 0xed, 0xd6, 0xef, 0xfe, 0xfe, 0xcf, 0x3f, 0x66, 0x6e, 0xaa, 0x75, 0x36, 0xdf, 0x5d, 0xde,
	0x6b, 0xd3, 0xe2, 0x6e, 0xc7, 0x2e, 0x87, 0x2f, 0x94, 0x26, 0x1a, 0x41, 0x41, 0x4c, 0x14, 0x68,
	0x5d, 0xaa, 0x88, 0x4d, 0x00, 0x0b, 0xc9, 0x3f, 0x63, 0xe4, 0xb7, 0xd5, 0x5b, 0x09, 0xf2, 0xef,
	0xc4, 0xfd, 0xf1, 0xaa, 0xcd, 0xee, 0xa7, 0xf6, 0x77, 0xf4, 0xdf, 0x2b, 0x64, 0x03, 0x44, 0xb3,
	0x05, 0xda, 0xe2, 0x43, 0x42, 0x7a, 0xd8, 0x78, 0x9b, 0xaa, 0xe6, 0x3b, 0xa9, 0x3a, 0x84, 0x3c,
	0x9f, 0x0a, 0x10, 0xe2, 0xf3, 0x58, 0x7c, 0xea, 0x50, 0xd7, 0x13, 0x32, 0xe1, 0xed, 0x6d, 0xc6,
	0xbf, 0xae, 0x55, 0x25, 0xbf, 0x6f, 0x5b, 0xce, 0xd4, 0xa5, 0xde, 0x11, 0x6c, 0x7d, 0x27, 0xc6,
	0x16, 0x8e, 0x13, 0x31, 0xb6, 0x68, 0x3c, 0x98, 0xcf, 0x66, 0x3b, 0x94, 0xed, 0x08, 0x0a, 0xa2,
	0x27, 0x47, 0x0b, 0xce, 0xaa, 0x6e, 0x30, 0xca, 0x54, 0xe7, 0xae, 0x6d, 0x30, 0xce, 0x2a, 0x5a,
	0x89, 0x7b, 0x00, 0x0d, 0xa0, 0x2c, 0x80, 0xfb, 0x2f, 0xfb, 0x5d, 0x11, 0xbe, 0xe4, 0x58, 0xb0,
	0x80, 0x4f, 0xd8, 0x88, 0xd6, 0x92, 0x1e, 0xb5, 0xcd, 0x57, 0xe8, 0x11, 0x94, 0xc2, 0x2e, 0x1a,
	0x6d, 0xf2, 0x4b, 0x39, 0x35, 0x15, 0xa8, 0x5b, 0x69, 0xb1, 0xa0, 0xdd, 0x64, 0xb4, 0xab, 0xa8,
	0x12, 0xa7, 0xf5, 0xd1, 0x61, 0xac, 0xf9, 0x97, 0x2f, 0xdf, 0x22, 0xea, 0x8f, 0x92, 0xe2, 0x74,
	0x1f, 0xaf, 0x2d, 0x21, 0x1d, 0x20, 0x6a, 0xb9, 0x17, 0xfa, 0x71, 0x51, 0x2e, 0x09, 0x4f, 0x36,
	0x93, 0x9e, 0xfc, 0x1a, 0xaa, 0x11, 0x27, 0x73, 0xe6, 0x96, 0x68, 0xf9, 0x53, 0xbd, 0xfd, 0x42,
	0x5e, 0xe1, 0xd1, 0xe6, 0x1c, 0x8f, 0x9a, 0xb0, 0x12, 0x6f, 0xe0, 0x51, 0x5d, 0xa4, 0xff, 0xcc,
	0x44, 0xa0, 0x6e, 0xcf, 0x59, 0x11, 0xe7, 0xde, 0x61, 0xfc, 0xdb, 0xda, 0x86, 0xe4, 0x37, 0xa6,
	0xc1, 0x45, 0x5b, 0xf4, 0xfa, 0x34, 0xb7, 0xce, 0xa1, 0x9a, 0xec, 0x65, 0x91, 0x1a, 0xbb, 0x5e,
	0x52, 0x0d, 0xa9, 0x7a, 0x7d, 0xee, 0x9a, 0xd0, 0x75, 0x9d, 0xe9, 0xda, 0xd4, 0x6a, 0x52, 0x97,
	0x6c, 0xd1, 0xa8, 0x9e, 0x21, 0x4b, 0xba, 0x50, 0xc9, 0x35, 0x99, 0x5f, 0x69, 0x0d, 0xf5, 0xd9,
	0x05, 0x41, 0x7f, 0x93, 0xd1, 0x5f, 0x43, 0x9b, 0x69, 0x7a, 0xee, 0xae, 0x8b, 0x54, 0x67, 0xfb,
	0x25, 0xf1, 0x58, 0xa4, 0xb7, 0xc3, 0xcc, 0x48, 0x37, 0xbd, 0xaa, 0x3a, 0x6f, 0x69, 0x51, 0xaa,
	0x87, 0xfd, 0x28, 0xc2, 0x50, 0x49, 0xec, 0x79, 0x5f, 0x15, 0x0b, 0x0f, 0xe4, 0xb7, 0x8d, 0xf1,
	0x18, 0x8d, 0x64, 0x72, 0xa5, 0x22, 0x33, 0x77, 0xa0, 0x58, 0x98, 0x60, 0x42, 0x49, 0x73, 0x81,
	0xd7, 0x06, 0x90, 0xe7, 0x6d, 0xad, 0xb8, 0xa8, 0x12, 0x9d, 0xb4, 0xb8, 0xa8, 0x92, 0x7d, 0xaf,
	0xd6, 0x60, 0x8c, 0x2a, 0xaa, 0xcf, 0x9a, 0xed, 0x31, 0xe4, 0xfe, 0xef, 0x95, 0x3f, 0x74, 0xbe,
	0x45, 0x5f, 0xc0, 0xea, 0x57, 0xc4, 0xb2, 0x6c, 0xc7, 0x6a, 0x18, 0xae, 0xdb, 0xe8, 0x9c, 0xf4,
	0xb5, 0x06, 0x94, 0x63, 0x22, 0x75, 0xed, 0x8c, 0x10, 0xf3, 0xe5, 0x25, 0xb9, 0x6f, 0xd1, 0x56,
	0xb5, 0x35, 0x22, 0x93, 0xbd, 0xe5, 0xbb, 0xad, 0x7b, 0xad, 0xbb, 0x4d, 0x45, 0xd9, 0xab, 0x19,
	0xae, 0x3b, 0xb6, 0x79, 0x63, 0xd6, 0xfe, 0x8d, 0x4f, 0x9c, 0x67, 0x37, 0x40, 0x85, 0xec, 0x57,
	0x4f, 0x4f, 0xd1, 0x7a, 0x31, 0xa3, 0x56, 0x3a, 0xd3, 0xe0, 0x82, 0x78, 0xf6, 0xb7, 0x0c, 0xd0,
	0xc8, 0x9c, 0x95, 0xa0, 0xc0, 0x57, 0x97, 0x9e, 0xe5, 0xdd, 0x33, 0x6a, 0xdb, 0x59, 0x9e, 0xf9,
	0xe2, 0x87, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x29, 0x75, 0xef, 0xa0, 0x1d, 0x15, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// APIServiceClient is the client API for APIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIServiceClient interface {
	CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*CreateAdminResponse, error)
	// Add permission
	AddPermission(ctx context.Context, in *AddPermissionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Add role
	AddRole(ctx context.Context, in *AddRoleRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Remove role
	RemoveRole(ctx context.Context, in *RemoveRoleRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Sign up user
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
	// Sign in user
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	// Get current user.
	GetUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetUserResponse, error)
	// Get user for provided id.
	GetUserByID(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	// List users.
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// List detailed users.
	ListUsersDetailed(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersDetailedResponse, error)
	// Delete current user.
	DeleteUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// Delete user for provided id.
	DeleteUserByID(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Refresh token.
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	// Create new tracking for current user.
	CreateTracking(ctx context.Context, in *CreateTrackingRequest, opts ...grpc.CallOption) (*CreateTrackingResponse, error)
	// Get tracking by id.
	GetTracking(ctx context.Context, in *GetTrackingRequest, opts ...grpc.CallOption) (*GetTrackingResponse, error)
	// List tracking for current user.
	ListTrackingsForUser(ctx context.Context, in *ListTrackingsRequest, opts ...grpc.CallOption) (*ListTrackingsResponse, error)
	// List trackings for all users.
	ListTrackings(ctx context.Context, in *ListTrackingsRequest, opts ...grpc.CallOption) (*ListTrackingsResponse, error)
	// Delete tracking by id.
	DeleteTracking(ctx context.Context, in *DeleteTrackingRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Create report for current user.
	// Create report for current user.
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
}

type aPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIServiceClient(cc grpc.ClientConnInterface) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*CreateAdminResponse, error) {
	out := new(CreateAdminResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/CreateAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) AddPermission(ctx context.Context, in *AddPermissionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.APIService/AddPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) AddRole(ctx context.Context, in *AddRoleRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.APIService/AddRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) RemoveRole(ctx context.Context, in *RemoveRoleRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.APIService/RemoveRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetUserByID(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/GetUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) ListUsersDetailed(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersDetailedResponse, error) {
	out := new(ListUsersDetailedResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/ListUsersDetailed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) DeleteUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.APIService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) DeleteUserByID(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.APIService/DeleteUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) CreateTracking(ctx context.Context, in *CreateTrackingRequest, opts ...grpc.CallOption) (*CreateTrackingResponse, error) {
	out := new(CreateTrackingResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/CreateTracking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetTracking(ctx context.Context, in *GetTrackingRequest, opts ...grpc.CallOption) (*GetTrackingResponse, error) {
	out := new(GetTrackingResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/GetTracking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) ListTrackingsForUser(ctx context.Context, in *ListTrackingsRequest, opts ...grpc.CallOption) (*ListTrackingsResponse, error) {
	out := new(ListTrackingsResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/ListTrackingsForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) ListTrackings(ctx context.Context, in *ListTrackingsRequest, opts ...grpc.CallOption) (*ListTrackingsResponse, error) {
	out := new(ListTrackingsResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/ListTrackings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) DeleteTracking(ctx context.Context, in *DeleteTrackingRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.APIService/DeleteTracking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServiceServer is the server API for APIService service.
type APIServiceServer interface {
	CreateAdmin(context.Context, *CreateAdminRequest) (*CreateAdminResponse, error)
	// Add permission
	AddPermission(context.Context, *AddPermissionRequest) (*empty.Empty, error)
	// Add role
	AddRole(context.Context, *AddRoleRequest) (*empty.Empty, error)
	// Remove role
	RemoveRole(context.Context, *RemoveRoleRequest) (*empty.Empty, error)
	// Sign up user
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
	// Sign in user
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	// Get current user.
	GetUser(context.Context, *empty.Empty) (*GetUserResponse, error)
	// Get user for provided id.
	GetUserByID(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// List users.
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	// List detailed users.
	ListUsersDetailed(context.Context, *ListUsersRequest) (*ListUsersDetailedResponse, error)
	// Delete current user.
	DeleteUser(context.Context, *empty.Empty) (*empty.Empty, error)
	// Delete user for provided id.
	DeleteUserByID(context.Context, *DeleteUserRequest) (*empty.Empty, error)
	// Refresh token.
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	// Create new tracking for current user.
	CreateTracking(context.Context, *CreateTrackingRequest) (*CreateTrackingResponse, error)
	// Get tracking by id.
	GetTracking(context.Context, *GetTrackingRequest) (*GetTrackingResponse, error)
	// List tracking for current user.
	ListTrackingsForUser(context.Context, *ListTrackingsRequest) (*ListTrackingsResponse, error)
	// List trackings for all users.
	ListTrackings(context.Context, *ListTrackingsRequest) (*ListTrackingsResponse, error)
	// Delete tracking by id.
	DeleteTracking(context.Context, *DeleteTrackingRequest) (*empty.Empty, error)
	// Create report for current user.
	// Create report for current user.
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
}

// UnimplementedAPIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServiceServer struct {
}

func (*UnimplementedAPIServiceServer) CreateAdmin(ctx context.Context, req *CreateAdminRequest) (*CreateAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAdmin not implemented")
}
func (*UnimplementedAPIServiceServer) AddPermission(ctx context.Context, req *AddPermissionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPermission not implemented")
}
func (*UnimplementedAPIServiceServer) AddRole(ctx context.Context, req *AddRoleRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRole not implemented")
}
func (*UnimplementedAPIServiceServer) RemoveRole(ctx context.Context, req *RemoveRoleRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRole not implemented")
}
func (*UnimplementedAPIServiceServer) SignUp(ctx context.Context, req *SignUpRequest) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedAPIServiceServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedAPIServiceServer) GetUser(ctx context.Context, req *empty.Empty) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedAPIServiceServer) GetUserByID(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByID not implemented")
}
func (*UnimplementedAPIServiceServer) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedAPIServiceServer) ListUsersDetailed(ctx context.Context, req *ListUsersRequest) (*ListUsersDetailedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsersDetailed not implemented")
}
func (*UnimplementedAPIServiceServer) DeleteUser(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedAPIServiceServer) DeleteUserByID(ctx context.Context, req *DeleteUserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserByID not implemented")
}
func (*UnimplementedAPIServiceServer) RefreshToken(ctx context.Context, req *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (*UnimplementedAPIServiceServer) CreateTracking(ctx context.Context, req *CreateTrackingRequest) (*CreateTrackingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTracking not implemented")
}
func (*UnimplementedAPIServiceServer) GetTracking(ctx context.Context, req *GetTrackingRequest) (*GetTrackingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTracking not implemented")
}
func (*UnimplementedAPIServiceServer) ListTrackingsForUser(ctx context.Context, req *ListTrackingsRequest) (*ListTrackingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTrackingsForUser not implemented")
}
func (*UnimplementedAPIServiceServer) ListTrackings(ctx context.Context, req *ListTrackingsRequest) (*ListTrackingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTrackings not implemented")
}
func (*UnimplementedAPIServiceServer) DeleteTracking(ctx context.Context, req *DeleteTrackingRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTracking not implemented")
}
func (*UnimplementedAPIServiceServer) Report(ctx context.Context, req *ReportRequest) (*ReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}

func RegisterAPIServiceServer(s *grpc.Server, srv APIServiceServer) {
	s.RegisterService(&_APIService_serviceDesc, srv)
}

func _APIService_CreateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).CreateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/CreateAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).CreateAdmin(ctx, req.(*CreateAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_AddPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).AddPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/AddPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).AddPermission(ctx, req.(*AddPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_AddRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).AddRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/AddRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).AddRole(ctx, req.(*AddRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_RemoveRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).RemoveRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/RemoveRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).RemoveRole(ctx, req.(*RemoveRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetUser(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetUserByID(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_ListUsersDetailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).ListUsersDetailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/ListUsersDetailed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).ListUsersDetailed(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).DeleteUser(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_DeleteUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).DeleteUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/DeleteUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).DeleteUserByID(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_CreateTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).CreateTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/CreateTracking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).CreateTracking(ctx, req.(*CreateTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetTracking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetTracking(ctx, req.(*GetTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_ListTrackingsForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrackingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).ListTrackingsForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/ListTrackingsForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).ListTrackingsForUser(ctx, req.(*ListTrackingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_ListTrackings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrackingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).ListTrackings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/ListTrackings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).ListTrackings(ctx, req.(*ListTrackingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_DeleteTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).DeleteTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/DeleteTracking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).DeleteTracking(ctx, req.(*DeleteTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAdmin",
			Handler:    _APIService_CreateAdmin_Handler,
		},
		{
			MethodName: "AddPermission",
			Handler:    _APIService_AddPermission_Handler,
		},
		{
			MethodName: "AddRole",
			Handler:    _APIService_AddRole_Handler,
		},
		{
			MethodName: "RemoveRole",
			Handler:    _APIService_RemoveRole_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _APIService_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _APIService_SignIn_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _APIService_GetUser_Handler,
		},
		{
			MethodName: "GetUserByID",
			Handler:    _APIService_GetUserByID_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _APIService_ListUsers_Handler,
		},
		{
			MethodName: "ListUsersDetailed",
			Handler:    _APIService_ListUsersDetailed_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _APIService_DeleteUser_Handler,
		},
		{
			MethodName: "DeleteUserByID",
			Handler:    _APIService_DeleteUserByID_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _APIService_RefreshToken_Handler,
		},
		{
			MethodName: "CreateTracking",
			Handler:    _APIService_CreateTracking_Handler,
		},
		{
			MethodName: "GetTracking",
			Handler:    _APIService_GetTracking_Handler,
		},
		{
			MethodName: "ListTrackingsForUser",
			Handler:    _APIService_ListTrackingsForUser_Handler,
		},
		{
			MethodName: "ListTrackings",
			Handler:    _APIService_ListTrackings_Handler,
		},
		{
			MethodName: "DeleteTracking",
			Handler:    _APIService_DeleteTracking_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _APIService_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
