FROM golang:1.14-alpine as builder

# TODO(boodyvo): Add mod install

RUN apk add --update git alpine-sdk
COPY . /app
WORKDIR /app/services/api/cmd/api-service/
RUN go install .
WORKDIR /app
COPY ./docs /docs

FROM alpine:3.11
COPY --from=builder /go/bin/ /bin
CMD ["api-service"]